# Archivo: render.yaml
services:
  - type: web
    name: nexus-ai-trading
    env: python
    branch: main
    buildCommand: pip install -r requirements.txt
    
    # ðŸ”¥ Comando de Inicio CORRECTO para FastAPI/Uvicorn
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    
    plan: free
    # Carpeta raÃ­z (donde estÃ¡ main.py)
    rootDir: .